R = '\033[31m' # Red
N = '\033[1;37m' # White
def a():
	print ""+N+""
	print "ALL  VIRUS COLLECTIONS"
	print "======================"
	print 
	print "name                                        rank"
	print "----                                        ----\033[31m"
	print "/modules/android/module_dataeater           normal"
	print "/modules/android/module_botloop             normal"
	print "/modules/android/module_funnys              manual"
	print "/modules/android/module_chis                manual"
	print "/modules/android/module_cht                 manual"
	print "/modules/android/module_cat                 good"
	print "/modules/android/module_thinkking           manual"
	print "/modules/android/module_elite               good"
	print "/modules/android/module_hellboy             normal"
	print "/modules/android/module_imagepets           manual"
	print "/modules/android/module_recipesmart         manual"
	print "/modules/android/module_prasesamor          manual"
	print "/modules/android/module_romaticpos          manual"
	print "/modules/android/module_kitchen             manual"
	print "/modules/android/module_laughter            manual"
	print "/modules/android/module_praces              manual"
	print "/modules/android/module_statets             manual"
	print "/modules/android/module_wnd                 normal"
	print "/modules/android/module_wifihonf            good"
	print "/modules/android/module_braintest           good"
	print "/modules/android/module_advancedobfus       normal"
	print "/modules/android/module_agent	            normal"
	print "/modules/android/module_badnews             good"
	print "/modules/android/module_bios                normal"
	print "/modules/android/module_blatansms           normal"
	print "/modules/android/module_candycorn           good"
	print "/modules/android/module_claco               normal"
	print "/modules/android/module_crdinformation      good"
	print "/modules/android/module_dropdialer          good"
	print "/modules/android/module_dsencryp            good"
	print "/modules/android/module_dendroid            good"
	print "/modules/android/module_fakebank            normal"
	print "/modules/android/module_fakecmcc            normal"
	print "/modules/android/module_fakedoc             normal"
	print "/modules/android/module_fakevalidation      normal"
	print "/modules/android/module_fobus               normal"
	print "/modules/android/module_masnu               normal"
	print "/modules/android/module_omg                 normal"
	print "/modules/android/module_opfake              normal"
	print "/modules/android/module_smsworker           normal"
	print "/modules/android/module_vietcon             normal"
	print "/modules/macosx/module_trinoids             not tested"
	print "/modules/macosx/module_nothing              not test"
	print "/modules/windows/module_req_eater           normal"
	print "/modules/windows/module_quis                normal"
	print "/modules/windows/module_ugly                normal"
	print "/modules/windows/module_sleepy              normal"
	print "/modules/windows/module_rip                 normal"
	print "/modules/windows/module_koce                normal"
	print "/modules/windows/module_capslock            funny :v"
	print "/modules/windows/module_rdc                 normal"
	print "/modules/windows/module_alay                normal"
	print "/modules/windows/module_zipbomb             low"
	print "/modules/windows/module_cmd                 normal"
	
if __name__ == "__main__":
	a()
